dataset: 'MNIST'
prp_type: 'relaxed'
num_parallel: 8
num_workers: 4
benchmarks_dir: '/home/afzal/tools/benchmarks/relaxed/mnist_fc'
log_dir: '/home/afzal/tools/marabou/logs/relaxed/mnist_fc'
main_file: '/home/afzal/tools/my_scripts/encod_marabou/constr_encod.py'
confs: [60, 80, 90, 95]