property: 'mod_prop'
dataset: 'MNIST' 
is_test_data: True
mean: [0.0]
std: [1.0]
preprocessing_dir: '/home/u1411251/tools/my_scripts'
net_dir: '/home/u1411251/tools/networks/conf_final/mnist/vnncomp'
images_csv_file: '/home/u1411251/tools/my_scripts/gans/results/images_csv.csv'
is_softmax: True
is_cnn: False
is_nilgiri: True
abcrown_config: 'mnist.yaml'
image_shape: [1,784,1]
is_gans_input: True
orcale_net_dir: '/home/u1411251/tools/networks/oracle_nets'
orcale_nets: ['mnist_relu_5_100.onnx', 'ffnnRELU__Point_6_500.onnx', 'ffnnRELU__PGDK_w_0.1_6_500.onnx', 'ffnnRELU__PGDK_w_0.3_6_500.onnx', 'convSmallRELU__Point.onnx', 'convSmallRELU__PGDK.onnx', 'convSmallRELU__DiffAI.onnx', 'convMedGRELU__Point.onnx', 'convBigRELU__DiffAI.onnx']
log_dir: '/home/u1411251/tools/result_dir/mod_prop1/logs_0_200'
result_csv: 'res_analysed.csv'
is_print_images: True

