property: 'vnncomp' # mod_prop
# property: 'mod_prop'
dataset: 'MNIST' #'CIFAR100' 
vnncomp_benchmarks_dir: '/home/afzal/tools/networks/vnncomp2022_benchmarks/benchmarks/mnist_fc'
preprocessing_dir: '/home/afzal/tools/my_scripts'
confs: [0, 60, 80, 90, 95]
timeout: 500
is_softmax: True
epsilons: [0.0039]
tolerance_param: -0.001
is_nilgiri: True
abcrown_config: 'mnist.yaml'
is_gans_input: False

