property: 'one_hop'
dataset: 'MNIST' 
is_test_data: True
mean: [0.0]
std: [1.0]
preprocessing_dir: '/home/afzal/tools/my_scripts'
net_dir: '/home/afzal/tools/networks/conf_final/mnist/vnncomp'
nets: ['mnist-net_256x2.onnx', 'mnist-net_256x4.onnx', 'mnist-net_256x6.onnx']
images_csv_file: '/home/afzal/tools/my_scripts/gans/results/images_csv.csv'
timeout: 500
is_softmax: True
tolerance_param: 0.001
is_cnn: False
is_nilgiri: True
abcrown_config: 'mnist.yaml'
image_shape: [1,784,1]
is_gans_input: True
log_dir: '/home/afzal/results/mod_prop/logs_70_73_200'

