property: 'fp' # mod_prop
# property: 'mod_prop'
dataset: 'MNIST' 
is_test_data: False
mean: [0.0]
std: [1.0]
vnncomp_benchmarks_dir: '/home/u1411251/tools/vnncomp_benchmarks/mnist_fc'
target_benchmarks_dir: '/home/u1411251/tools/fp'
nets: ['mnist-net_256x2.onnx']
dataset_idxs_file: '/home/u1411251/tools/my_scripts/oracle/indices.txt'
timeout: 120
epsilons: [0.06]
abcrown_config: 'mnist.yaml'
image_shape: [1,784,1]
is_gans_input: False
