property: 'mod_prop'
dataset: 'MNIST' 
is_test_data: True
mean: [0.0]
std: [1.0]
preprocessing_dir: '/home/ruhy/tools/my_scripts'
net_dir: '/home/ruhy/tools/networks/conf_final/mnist/vnncomp'
nets: ['mnist-net_256x2.onnx', 'mnist-net_256x4.onnx', 'mnist-net_256x6.onnx']
dataset_idxs_file: '/home/ruhy/tools/networks/conf_final/mnist/selected_idxs_mnist.txt'
images_csv_file: '/home/ruhy/tools/my_scripts/gans/results/images_csv.csv'
confs: [70]
timeout: 500
image_indexes_range: [0, 100]
is_softmax: True
epsilons: [0.06]
tolerance_param: 0.001
is_cnn: False
is_nilgiri: True
abcrown_config: 'mnist.yaml'
image_shape: [1,784,1]
is_gans_input: True

