property: 'vnncomp' # mod_prop
sub_property: 'smoothness'
# property: 'mod_prop'
dataset: 'MNIST' #'CIFAR100' 
vnncomp_benchmarks_dir: '/home/afzal/tools/vnncomp_benchmarks/mnist_fc'
target_benchmarks_dir: '/home/afzal/tools/benchmarks/smoothness/mnist_fc'
log_dir: '/home/afzal/tools/logs/smoothness/mnist_fc'
conf_file: '/home/afzal/tools/vnncomp_benchmarks/mnist_fc/conf_mnist.csv'
confs: [10, 25, 40]
timeout: 500
is_softmax: True
epsilons: [0.0039]
tolerance_param: 0.00001
is_nilgiri: False
abcrown_config: 'abcrown_tool_run_scripts/ab_crown_configs/mnist.yaml'
abcrown_tool: 'external_tools/alpha-beta-CROWN/complete_verifier/abcrown.py'
is_less_than_output_prp: False
is_target_prop: False
device: 'cpu'